global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "planner-ai"
    metrics_path: /metrics
    static_configs:
      - targets: ["planner-ai-backend:8000"]

  - job_name: "kepler"
    metrics_path: /metrics
    static_configs:
      - targets: ["kepler.kepler-system.svc.cluster.local:9103"]
    scrape_interval: 5s
